# Generated by Django 2.1.7 on 2019-04-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('rollNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('programme', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('uniqueID', models.AutoField(primary_key=True, serialize=False)),
                ('rollNumber', models.IntegerField(blank=True, default=0)),
                ('submission', models.CharField(max_length=50)),
                ('questionNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerGrader.Question')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peerGrader.Submission'),
        ),
        migrations.AddField(
            model_name='marks',
            name='checked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerGrader.Student'),
        ),
        migrations.AddField(
            model_name='marks',
            name='submission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerGrader.Submission'),
        ),
    ]
